workflows:
  build_macos_both:
    name: Build Electron App for macOS (Both Architectures)
    instance_type: mac_mini_m2
    max_build_duration: 45
    environment:
      vars:
        NODE_ENV: production
    scripts:
      - name: Install dependencies
        script: |
          npm ci  # Use ci instead of install for CI environments
          # Verify electron-builder is installed
          npx electron-builder --version
      - name: Build for both architectures
        script: |
          npx electron-builder --mac --x64 --arm64

    artifacts:
      - dist/*.dmg
      - dist/*.zip
      - dist/**/*.app
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules

