workflows:
  build_macos_both:
    name: Build Electron App for macOS (Both Architectures)
    instance_type: mac_mini_m2
    max_build_duration: 45
    environment:
      vars:
        NODE_ENV: production
      node: 18
    scripts:
      - name: Clean and install dependencies
        script: |
          # Clean install to ensure all dependencies are properly installed
          rm -rf node_modules package-lock.json
          npm install
          
          # Verify installations
          npx electron --version
          npx electron-builder --version
          
      - name: Build for both architectures
        script: |
          # Build for both architectures
          npx electron-builder --mac --x64
          npx electron-builder --mac --arm64
          
    artifacts:
      - dist/*.dmg
      - dist/*.zip
      - dist/**/*.app
      
    cache:
      cache_paths:
        - $HOME/.npm